org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
bidscube.version=1.2.6

android.useAndroidX=true
kotlin.code.style=official

android.nonTransitiveRClass=true
mavenCentralUsername=38SpWV
mavenCentralPassword=tpaB7x1gSbJ71QRqj87wpp898uALhyYj5
signing.keyIdLong=531493461C66BE7B0CF7791279B7C1BC53484B17
signing.keyId=79B7C1BC53484B17
signing.password=Au9x8cT9G0ycd7q70azx
signing.secretKeyRingFile=./keys/private-gpg.asc
signing.secretKeyRingFileBase64=./keys/private-gpg.asc.base64